language: python
python:
- '2.7'
- '3.5'
- '3.6'
sudo: required
services:
  - docker

before_install:
 - pip install pytest

install:
 - python setup.py sdist
 - pip install dist/DockerMake*.tar.gz



env:
  global:
  - secure: nErzhf1a/OX7wn7ecFtP+amy99THp0SSkm7qT6Tz4UyFyT1wTC0T/Py4N/Wv/U+azY4WArapRhszdvCMx2t8LfpfPIOCpxsPG6juRqhCpSk8lW3tYPD5+899Anwd2CPql4Sbq+BFNT67P4J9OcmQnHPXZ57lE+0CLZ5VoXJuV5OFhrPaPg/vA2AV0KbtK8tz/vZ6ElwP1sv9Yqra2tau2VfEe1SYZER/eAPQTOVLmO1iXz54cAJrVNz1nfwvGouwWeopXIKCI43IUs2q6UaWvfTOLvsx8vodEO9k520s1IbVPYUaMal5L2hkJremBSIjjGfCCRCDVZE64w8gA2Q3fgQwcUJfpycbwP9VlX+3dkQi83/WXJnawhxnXaCG0Ut7dutGfiTH8LOBSZsaS9umOW1Zk9U6Oqxgg8bSX+12tpNW3swphWxhRqMWlh8PEuKfL08FhEVew0M+++f3Hk+rzFIoH1kbNl4s9TU1P0RjNyZoAfp/Hx+/4c07RJ72eRxgq5pd+mIY5Efw5PTDWPXiXhmDtYkZ9PLNolmMMZFT8Ty/kEHjQao9fsLp4NrVtxInNz/OPkNHtj9kSkZLk60MZcCW9E+hCsMYqUO7+MDJdKh35xuqaY9AhS2MGTxs7YVfJ4fBKkMxzAwMVLxzkeT8D/ivRqfVQnT2EevQdbH8mHs=
  - secure: cMay8VLpap0udyZL7xwmKQsen3W7K4fD34GaC1sG+39Kb4vXD9GoMSaGjRz3kd5pQt1TNuVSui2HA9Py0iJWadZghABHgHAdNGoVSI+cdtIDQLLE4DWGcHD/UBpLxEYHMiDdtZ8bgb4sZL5UG43ZZZhf2nQH3VCBmxGIm4h6406rtCzlj7Q4DK7riguwCplaNKUBOwf1vy337W19MDJGkAqTpKmTMXCvjko70xd4RGN+GAhB+1pWxahli+2l8UBhaUnqbGKAq/o0Fqo0UtCcDMxo/MfyBU7OY1L9+SQjZw98aeQOlIyreLmTbhASyy4lCr3VM5ta2rWdv/KYXhi0gkJn7j31jUEhxsV4W44+uX646TKuh0V+VKI6OIUicJjRHrNU1LcDti260VHoihk/A1sF0WTfJ90zRudADm5DJ6KZClBeUmNg1MXSlNDvTOVi3H1IFA7lztpioaahPgMm8NuVx1e+ojNrzHEdeI+WLyk62iAlOaghw/Uj7TY8bFhuu4ZPqMOYZFq9FgYAK2toTPKZeWS2w//9VPeOm/2ucgjavqyzLSkrURanDCV7mrMH9JMEG5mw6IN+vmHCqXz0WvK/dAkzlMFP/WAzJAfCKDO61GMeqVV5TxxaWSSCqjZS4DAD0QRECGUik/1riGv0IMk9xEzfyLUsLiyZYH7VrXg=
  - secure: NK7FSFtknE97YcnwpzLjIjKfsh/awxv82MFNl2/0qs9brY5TmEqd/gKZDPoOGdHNZDRFXMgTmvntF7DFXQvqSuYOnxcBtbwwLTKdXWhbZNSdNWm2OLUf8hiTLrLE/i53wN4ZhycMwkphrPRQzR/gGFajNKSH355pjON5XbeUOeeNbUZ+gDt9jW2HfKSicdcIjTQ+Sq53ScGYySmLDnL8QezVunnh9wQpzwf7p6R4clihF7ZXiQuzP7tPgf2G7GE//XwXc7T7rv9inarTgfeU7SchdSHcDxiLdNGBQExayySzRyM6gGhtDxxUX3wwiMV0TlvPW5ZbbLgwnOvOdVq5g2hvtJ0B3Ow/aXZR81grwyMOzcoyNKGtePs2zWhFn9zVagqZRf1ebH7+Sk/SMHDbDsABNCMxwi0ctAJiKOYtPMhGM0QnDJwEzswjGcnTVeUw+GZwAOemZtmMrtG++EYMcTAoBrc6O+blj1NllcIQTczGzfvwFxsvlueL92ub6IhcxNEvTi6Z+/QTIbW3Lm9247DzCsIpb/4jv8UwUl2ZjO+v/HBr8e95k9K7gRNr0rR6Dcs4KcMZVXQ4hSBrBtciWwSZIcIUNUEiEw/6V9k+ufJond19Ci79/iWtxqrzl2OAneKtFEsLh9HjFb5Q1y2BI6iuDL6nl94tLkeYo6N9Ilg=
  - secure: O2PkPoZfR9ljapP57wG29iO58n2oMQiGEDg49jBIiazldBAqv7MLLjGtZTCKJrS+yBrkhs3IoprLW6QyLxHlXpLj9FSpeTZyst13Hvvqf5TyxSig8hKmE6XbpEyU0PcKRZPUhnu+lHJxd6Do70tyCMAIrsWgdBgEcJIwcRZh4M8g70SAaTEFr5ZRvauIgXbNeFzr/Idc/MtOmaV/veYzoTlQcBBqjsydWoZOIN7XptNPJexFtQdn9wF/goZfo4PyoSBHstT4vr3Xwc3IVI1tFfT5jC7c6lFSjSatNnKEj5/4+NyC+SuYpQZ0IkJQT3O2xM/DZYKFM0w4+0xBD6wCdZKEKazO8xFl3RKXGBOt9C5Xy+ZKj9YMTHw0bHkL4DrwpAE3x13fjiJuBnMghxFeXC2i77JGspwZn2u0MbkYSjAIX7nnkFQXjSnFgmPB0OmRrL4oTd8+p8W/oIfk7D3xENXNfBfAPttFncKlFBPjF7MrNVRxSr6bbo7OEBDGoG6OuNMsSB8bQmCm/wSl5N4/OF1UrRUN65SV4o8504ImDFeDtLvfNms7Xt6pczhPU1I3CFeBwUQYdoRocKjiR3h1Q8mbaRBarP97wVqbzReeEHwrAdeh+NyUufSfd+hGwYZgI0x0i9SStghe4kvfXe7iAlGCWS5ZZZrv8etx73cJYbQ=



jobs:
  include:
    - stage: test
      script: cd test && py.test

    - stage: deploy
      python: '3.6'
      deploy:
        provider: pypi
        user: avirshup
        password:
          secure: "rGzw+J6etPMntTy6jZqVmGukHq+tFStcVnYeaVcsMrRZBbE5ilffaCBwp52jVqFW/zGAv0rdDSrb1ixPXNTKfe2Rrl4QejqJlbd6TujlanI2TZiDOmzaexKYe24yg6a4k3hBW3IjVyjvDHyvGWkVMHHs+dpsCO7v2ZqcKcoiPEnjPFD40uWgKXK46GCRd0TYrq15znKdwz0uR1U+NMhGi6JbWznpMPYJ7BHMBua5vm+hMcMQvZlgmylf7pf8D9dabRjrPOuwweIMsuI/huONzmeQc8JeEb/16eNXpPVuM0R9pyaGJuFHVqQYrhW29bgWuj0/GAzFUAR69uIisBU1s9TjGunXGRW0Tq2Xb+JvUeKHIeG9GEb072JO/9K50097pnYEb7dUn975NRIJOYWWrpnmMJJDHje4beEjc5q6w0P/roklVLEt7ob+o8mQsXxXDljZ/kWmJMhGjNx1chAACIGHHFk5ikqsAS7e1jyKS+mMcC+wRx9kCnpknktDCH2GT0b5TZmlpr8easaVCKuyESi9W9l6JaWZAz+kSpfDWmYvy71NpMVMWGLGbiwR3spqNr5Kr6SgE99l/E+KsoHJ3znqSSwaO+RPH6VomDjnFNe+TJwsa9fzI6kkPoM/DJdLNtYnzhanzquSVoNjlx68o7dU82GN8COLCT51a6BmrEQ="
